"""add_status_to_chunk_and_doucment_tables

Revision ID: 39015ae510e0
Revises: 29e0e8f6dd42
Create Date: 2025-04-13 15:10:33.098054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39015ae510e0'
down_revision: Union[str, None] = '29e0e8f6dd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add status columns as nullable first
    op.add_column('document_chunks', sa.Column('status', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(), nullable=True))
    
    # Step 2: Set default values for existing rows
    op.execute("UPDATE document_chunks SET status = 'pending' WHERE status IS NULL")
    op.execute("UPDATE documents SET status = 'pending' WHERE status IS NULL")
    
    # Step 3: Make the columns NOT NULL and set server default
    op.alter_column('document_chunks', 'status',
               existing_type=sa.String(),
               nullable=False,
               server_default='pending')
    op.alter_column('documents', 'status',
               existing_type=sa.String(),
               nullable=False,
               server_default='pending')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    op.drop_column('document_chunks', 'status')
    # ### end Alembic commands ###
